### ISSUE TITLE
Bug Report: Incorrect Flight Time Calculation

### ISSUE THREAD

**Issue by mahmudhassan5** [cathaypacific8747/am4#11]
The algorithm currently provides incorrect flight times for certain routes. For example, the flight time from LAD (Luanda, Angola) to HTDA (Dar es Salaam, Tanzania) should be 3.25 hours, but the algorithm is returning 2.17 hours. This discrepancy affects the accuracy of the calculations and could impact decision-making within the application.

**Comment by mahmudhassan5** [comment]
Sorry didn’t pay attention to realism

**Comment by cathaypacific8747** [comment]
Be sure to specify the correct gamemode and modifiers (speed, 4x etc.), if applicable
